"use client";

import jsPDF from "jspdf";
import { Download } from "lucide-react";
import type { AnalysisPayload } from "@/lib/types";

interface ReportButtonProps {
  analysis: AnalysisPayload;
}

export function ReportButton({ analysis }: ReportButtonProps) {
  async function exportReport() {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    const addText = (text: string, x: number, yPos: number, size = 10, font = "helvetica", style = "normal", color = "#000000") => {
      doc.setFont(font, style);
      doc.setFontSize(size);
      doc.setTextColor(color);
      doc.text(text, x, yPos);
    };

    const addLine = (yPos: number) => {
      doc.setDrawColor(230, 230, 230);
      doc.line(20, yPos, pageWidth - 20, yPos);
    };

    // --- Header ---
    addText("RESUME ANALYSIS REPORT", 20, y, 10, "helvetica", "bold", "#6366f1");
    y += 10;
    addText(analysis.parsedResume.name.toUpperCase(), 20, y, 22, "helvetica", "bold", "#000000");
    y += 10;
    addText(`${analysis.parsedResume.email || "No email"} | ${analysis.parsedResume.phone || "No phone"}`, 20, y, 10, "helvetica", "normal", "#666666");
    y += 15;
    addLine(y);
    y += 15;

    // --- Score Section ---
    doc.setFillColor(245, 247, 250);
    doc.rect(20, y, (pageWidth - 50) / 2, 30, "F");
    addText("ATS SCORE", 25, y + 10, 8, "helvetica", "bold", "#666666");
    addText(`${analysis.atsScore}/100`, 25, y + 22, 20, "helvetica", "bold", "#000000");

    doc.rect(pageWidth / 2 + 5, y, (pageWidth - 50) / 2, 30, "F");
    addText("JOB MATCH", pageWidth / 2 + 10, y + 10, 8, "helvetica", "bold", "#666666");
    addText(`${analysis.matchScore || 0}%`, pageWidth / 2 + 10, y + 22, 20, "helvetica", "bold", "#000000");
    y += 45;

    // --- Summary ---
    addText("AI EXECUTIVE SUMMARY", 20, y, 12, "helvetica", "bold", "#000000");
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor("#444444");
    const summaryLines = doc.splitTextToSize(analysis.aiFeedback.summary, pageWidth - 40);
    doc.text(summaryLines, 20, y);
    y += (summaryLines.length * 5) + 15;

    // --- Strengths & Weaknesses ---
    const drawList = (title: string, items: string[], xPos: number, color: string) => {
      let currentY = y;
      addText(title.toUpperCase(), xPos, currentY, 10, "helvetica", "bold", color);
      currentY += 8;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor("#444444");
      items.slice(0, 5).forEach(item => {
        const lines = doc.splitTextToSize(`• ${item}`, (pageWidth - 50) / 2);
        doc.text(lines, xPos, currentY);
        currentY += (lines.length * 5) + 2;
      });
      return currentY;
    };

    const yStrengths = drawList("Key Strengths", analysis.aiFeedback.strengths, 20, "#10b981");
    const yWeaknesses = drawList("Areas for Improvement", analysis.aiFeedback.weaknesses, pageWidth / 2 + 5, "#ef4444");
    
    y = Math.max(yStrengths, yWeaknesses) + 15;

    // --- Suggestions ---
    addText("ACTIONABLE RECOMMENDATIONS", 20, y, 12, "helvetica", "bold", "#000000");
    y += 10;
    analysis.aiFeedback.suggestions.slice(0, 6).forEach(item => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFillColor(240, 244, 255);
        doc.circle(23, y - 1, 1, "F");
        const lines = doc.splitTextToSize(item, pageWidth - 50);
        doc.text(lines, 28, y);
        y += (lines.length * 5) + 4;
    });

    y += 10;
    addText("REWRITTEN IMPACT BULLETS", 20, y, 12, "helvetica", "bold", "#000000");
    y += 10;
    analysis.aiFeedback.rewrittenBullets.slice(0, 3).forEach(item => {
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setDrawColor(99, 102, 241);
        doc.setLineWidth(0.5);
        doc.line(20, y, 20, y + 10);
        const lines = doc.splitTextToSize(item, pageWidth - 50);
        doc.text(lines, 25, y + 4);
        y += (lines.length * 5) + 10;
    });

    // --- Footer ---
    doc.setFontSize(8);
    doc.setTextColor("#aaaaaa");
    doc.text(`Generated by ResumeIQ AI Analyzer on ${new Date().toLocaleDateString()}`, 20, 285);

    doc.save(`Resume-Analysis-${analysis.parsedResume.name.replace(/\s+/g, "-")}.pdf`);
  }

  return (
    <button onClick={exportReport} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white px-4 py-3 text-sm font-black text-black shadow-[0_0_34px_rgba(255,255,255,0.12)] transition hover:-translate-y-0.5 hover:bg-cyan-200">
      <Download size={17} />
      Export professional report
    </button>
  );
}
